#include "gtest/gtest.h"
#include "validation.hpp"

std::string EMPTY_PASSWORD = "";
std::string PROPER_PASSWORD = "abcABC123!@#";
std::string TOO_SHORT_PASSWORD = "12345678";
std::string NO_DIGIT_IN_PASSWORD = "abcABC!@#";
std::string NO_SPECIAL_CHARACTER_IN_PASSWORD = "abcABC123";
std::string NO_UPPERCASE_CHARACTER_IN_PASSWORD = "abc123!@#";
auto MIN_ALLOWED_ERROR_CODE = ErrorCode::Ok;
auto MAX_ALLOWED_ERROR_CODE = ErrorCode::PasswordNeedsAtLeastOneUppercaseLetter;

TEST(DoesPasswordsMatchTests, returnsTrueForIdenticalPasswords)
{
    EXPECT_TRUE(doesPasswordsMatch(EMPTY_PASSWORD, EMPTY_PASSWORD));
    EXPECT_TRUE(doesPasswordsMatch(PROPER_PASSWORD, PROPER_PASSWORD));
    EXPECT_TRUE(doesPasswordsMatch(TOO_SHORT_PASSWORD, TOO_SHORT_PASSWORD));
    EXPECT_TRUE(doesPasswordsMatch(NO_DIGIT_IN_PASSWORD, NO_DIGIT_IN_PASSWORD));
    EXPECT_TRUE(doesPasswordsMatch(NO_SPECIAL_CHARACTER_IN_PASSWORD, NO_SPECIAL_CHARACTER_IN_PASSWORD));
    EXPECT_TRUE(doesPasswordsMatch(NO_UPPERCASE_CHARACTER_IN_PASSWORD, NO_UPPERCASE_CHARACTER_IN_PASSWORD));
}

TEST(DoesPasswordsMatchTests, returnsFalseForDifferentPasswords)
{
    EXPECT_FALSE(doesPasswordsMatch(EMPTY_PASSWORD, PROPER_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(PROPER_PASSWORD, EMPTY_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(PROPER_PASSWORD, TOO_SHORT_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(EMPTY_PASSWORD, TOO_SHORT_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(EMPTY_PASSWORD, NO_DIGIT_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(EMPTY_PASSWORD, NO_SPECIAL_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(EMPTY_PASSWORD, NO_UPPERCASE_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(PROPER_PASSWORD, NO_DIGIT_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(PROPER_PASSWORD, NO_SPECIAL_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(PROPER_PASSWORD, NO_UPPERCASE_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(TOO_SHORT_PASSWORD, EMPTY_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(TOO_SHORT_PASSWORD, NO_DIGIT_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(TOO_SHORT_PASSWORD, NO_SPECIAL_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(TOO_SHORT_PASSWORD, NO_UPPERCASE_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_DIGIT_IN_PASSWORD, EMPTY_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_DIGIT_IN_PASSWORD, PROPER_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_DIGIT_IN_PASSWORD, TOO_SHORT_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_DIGIT_IN_PASSWORD, NO_SPECIAL_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_DIGIT_IN_PASSWORD, NO_UPPERCASE_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_SPECIAL_CHARACTER_IN_PASSWORD, EMPTY_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_SPECIAL_CHARACTER_IN_PASSWORD, PROPER_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_SPECIAL_CHARACTER_IN_PASSWORD, TOO_SHORT_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_SPECIAL_CHARACTER_IN_PASSWORD, NO_DIGIT_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_SPECIAL_CHARACTER_IN_PASSWORD, NO_UPPERCASE_CHARACTER_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_UPPERCASE_CHARACTER_IN_PASSWORD, EMPTY_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_UPPERCASE_CHARACTER_IN_PASSWORD, PROPER_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_UPPERCASE_CHARACTER_IN_PASSWORD, TOO_SHORT_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_UPPERCASE_CHARACTER_IN_PASSWORD, NO_DIGIT_IN_PASSWORD));
    EXPECT_FALSE(doesPasswordsMatch(NO_UPPERCASE_CHARACTER_IN_PASSWORD, NO_SPECIAL_CHARACTER_IN_PASSWORD));
}

TEST(checkPasswordRulesTests, returnsValuesBetweenOkAndPasswordNeedsAtLeastOneUppercaseLetter) {
    EXPECT_GE(checkPasswordRules(EMPTY_PASSWORD), MIN_ALLOWED_ERROR_CODE);  // greater or equal >=
    EXPECT_LE(checkPasswordRules(EMPTY_PASSWORD), MAX_ALLOWED_ERROR_CODE);  // less or equal <=
    EXPECT_GE(checkPasswordRules(TOO_SHORT_PASSWORD), MIN_ALLOWED_ERROR_CODE);
    EXPECT_LE(checkPasswordRules(TOO_SHORT_PASSWORD), MAX_ALLOWED_ERROR_CODE);
}

TEST(checkPasswordTests, returnsValuesBetweenOkAndPasswordNeedsAtLeastOneUppercaseLetter) {
    EXPECT_GE(checkPassword(PROPER_PASSWORD, PROPER_PASSWORD), MIN_ALLOWED_ERROR_CODE);
    EXPECT_LE(checkPassword(PROPER_PASSWORD, PROPER_PASSWORD), MAX_ALLOWED_ERROR_CODE);
}

TEST(checkPasswordTests, returnsPasswordsDoesNotMatchForDifferentPasswords) {
    EXPECT_EQ(checkPassword(PROPER_PASSWORD, EMPTY_PASSWORD), ErrorCode::PasswordsDoesNotMatch); // equal ==
    EXPECT_EQ(checkPassword(EMPTY_PASSWORD, PROPER_PASSWORD), ErrorCode::PasswordsDoesNotMatch);
    EXPECT_EQ(checkPassword(TOO_SHORT_PASSWORD, PROPER_PASSWORD), ErrorCode::PasswordsDoesNotMatch); 
}

TEST(getErrorMessageTests, returnsErrorCodeAsString) {
    EXPECT_EQ(getErrorMessage(ErrorCode::Ok), "OK");
    // Add other tests for getErrorMessage if you wish
}